=== MinervaTools/PermIndex/meta/data.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/MinervaTools/PermIndex/blob/main/meta/data.schema.json",
    "title": "Permission Index",
    "description": "A group of permissions on the index.",
    "type": "array",
    "items": {
        "description": "A single permission",
        "type": "object",
        "required": ["name", "set"],
        "properties": {
            "name": {
                "description": "The name of the permission (e.g. my_plugin.test.permission or my_plugin.*.permission)",
                "type": "string"
            },
            "set": {
                "description": "Set this permission is a part of",
                "type": "string"
            },
            "description": {
                "description": "Description of the permission",
                "type": "string"
            },
            "match": {
                "description": "Regex matcher for wildcard-permissions",
                "type": "string"
            },
            "default": {
                "description": "Default permission state",
                "type": "string",
                "enum": ["true", "op", "false"]
            },
            "affectedCommands": {
                "description": "Array of commands this permission affects",
                "type": "array",
                "items": {
                    "description": "An affected command.",
                    "type": "object",
                    "required": "command",
                    "properties": {
                        "command": {
                            "description": "The name of the affected command without the leading / (e.g. 'gamemode' or 'myplugin manage')",
                            "type": "string"
                        },
                        "comment": {
                            "description": "The way in which the command is affected",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== MinervaTools/PermIndex/data/spigot/bukkit/bukkit.json
[
    {
        "name": "bukkit.broadcast",
        "description": "Receive broadcasts",
        "default": "true",
        "set": "bukkit"
    },
    {
        "name": "bukkit.broadcast.scradmin",
        "description": "Receive administrative broadcasts",
        "default": "op",
        "set": "bukkit"
    },
    {
        "name": "bukkit.broadcast.user",
        "description": "Receive user broadcasts",
        "default": "true",
        "set": "bukkit"
    },
    {
        "name": "bukkit.command.help",
        "description": "Allow viewing command-help",
        "default": "true",
        "set": "bukkit",
        "affectedCommands": [
            {
                "command": "help"
            }
        ]
    },
    {
        "name": "bukkit.command.plugins",
        "description": "Allow listing installed plugins",
        "default": "true",
        "set": "bukkit",
        "affectedCommands": [
            {
                "command": "plugins"
            }
        ]
    },
    {
        "name": "bukkit.command.restart",
        "description": "Allow restarting the server",
        "default": "op",
        "set": "spigot",
        "affectedCommands": [
            {
                "command": "restart"
            }
        ]
    },
    {
        "name": "bukkit.command.timings",
        "description": "Allow access to server timing controls",
        "default": "op",
        "set": "bukkit",
        "affectedCommands": [
            {
                "command": "timings on"
            },
            {
                "command": "timings off"
            },
            {
                "command": "timings merged"
            },
            {
                "command": "timings seperate"
            },
            {
                "command": "timings paste"
            },
            {
                "command": "timings reset"
            }
        ]
    },
    {
        "name": "bukkit.command.tps",
        "description": "Allow querying the TPS (ticks-per-second) of the server",
        "default": "op",
        "set": "spigot",
        "affectedCommands": [
            {
                "command": "tps"
            }
        ]
    },
    {
        "name": "bukkit.command.version",
        "description": "Allow viewing the server version",
        "default": "true",
        "set": "bukkit",
        "affectedCommands": [
            {
                "command": "version"
            }
        ]
    }
]
